services:
  - type: web
    name: dash-app
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      ./download_data.sh
    startCommand: gunicorn --workers=4 --threads=2 --timeout=60 app:server
    envVars:
      - key: PORT
        value: 8080  # Render automatically sets this, but you can override
      - key: DEBUG
        value: "False"services:
  - type: web
    name: dash-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
